runtime: python

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT config.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

# See https://cloud.google.com/appengine/docs/flexible/python/reference/app-yaml#services
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100
# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
# the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  SECRET_KEY: '' # This is a secret stored in GCP Secrets Manager and loaded during the build
  DEBUG: 'False' # always False for deployment
  
# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/

  DB_HOST: '/cloudsql/clover-gcp:us-central1:clover-gcp' #PROJECT SPECIFIC #cloud sql path
  DB_PORT: '5432' # PostgreSQL port
  DB_NAME: 'postgres'
  DB_USER: 'postgres' # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: '' # This is a secret stored in GCP Secrets Manager and loaded during the build

  STATIC_URL: 'https://storage.googleapis.com/clover-gcp_static/static/' ##PROJECT SPECIFIC # this is the url that you sync static files to

  GOOGLE_APPLICATION_CREDENTIALS: 'cloud-key-storage.json'
  
handlers:
- url: /asset-viewer
  static_dir: asset-viewer

- url: (/.*\.(ttf|eot|svg|woff|gif|jpg|png|ico))
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  secure: always
  expiration: 21d

- url: /images
  static_dir: static/images

- url: /static
  static_dir: static
  
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: clover-gcp:us-central1:clover-gcp #PROJECT SPECIFIC #cloud sql path

runtime_config:
  python_version: 3 # enter your Python version BASE ONLY here. Enter 2 for 2.7 or 3 for 3.7