# Generated by Django 3.2.12 on 2022-02-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clover', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Account',
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': '1. Application', 'verbose_name_plural': '1. Applications'},
        ),
        migrations.AlterModelOptions(
            name='applicationapikey',
            options={'ordering': ['-application', '-created'], 'verbose_name': '2. Application API key',
                     'verbose_name_plural': '2. Application API keys'},
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '3. Account', 'verbose_name_plural': '3. Accounts'},
        ),
        migrations.AlterModelOptions(
            name='trainingdataset',
            options={'verbose_name': '4. Training Data Set', 'verbose_name_plural': '4. Training Data Sets'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '5. Configuration', 'verbose_name_plural': '5. Configurations'},
        ),
        migrations.AlterModelOptions(
            name='clvmodel',
            options={'verbose_name': '6. CLV Model', 'verbose_name_plural': '6. CLV Models'},
        ),
        migrations.AlterField(
            model_name='trainingdataset',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_data',
                                    to='clover.account'),
        ),
        migrations.AlterField(
            model_name='config',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_config',
                                    to='clover.account'),
        ),
        migrations.AlterField(
            model_name='clvmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_clvmodel',
                                    to='clover.account'),
        ),
        migrations.RenameField(
            model_name='clvmodel',
            old_name='client',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='client',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='trainingdataset',
            old_name='client',
            new_name='account',
        ),
    ]
