# Generated by Django 3.2.12 on 2022-03-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clover', '0003_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clvmodel',
            name='data_fields',
            field=models.JSONField(help_text='Enter all of fields that are contained in your data set along with their data type, and whether they are Nullable or Required. Here is an example on how to enter one feature: [  {    "name": "feature_1",     "type": "STRING",     "mode": "Nullable"  }]'),
        ),
        migrations.AlterField(
            model_name='trainingdataset',
            name='data_fields',
            field=models.JSONField(help_text='Enter all of fields that are contained in your data set along with their data type, and whether they are Nullable or Required. Here is an example on how to enter one feature: [  {    "name": "feature_1",     "type": "STRING",     "mode": "Nullable"  }]'),
        ),
    ]
